### ISSUE TITLE
add support for Groq

### ISSUE THREAD

**Issue by jtoy** [AugustDev/enchanted#61]
I  dont think it makes sense to support tons of other models, but since groq is 10x faster and has free api keys to mixtral at 30 reqs a minute, I think worth it :)
https://groq.com/

**Comment by omniwired** [comment]
I think the whole point of this project is to allow local LLM via ollama to be run easily.

**Comment by adrianliechti** [comment]
You can use an LLM Gateway for such usecases.
Mine should work for that use case also: https://github.com/adrianliechti/llama

<img width="1220" alt="image" src="https://github.com/AugustDev/enchanted/assets/343775/ef8c8030-85e1-4ba6-9a5c-cb6a3e30e3fe">


Enchanted Settings:

<img width="1220" alt="image" src="https://github.com/AugustDev/enchanted/assets/343775/cb423a31-9b55-4290-8490-1130a5086e18">

LLM Platform Config:

config.yaml
```yaml
providers:
  - type: groq
    token: ${GROQ_API_TOKEN}

    models:
      llama3-70b-instruct:
        id: llama3-70b-8192
      
      mixtral-8x7b-instruct:
        id: mixtral-8x7b-32768
```
